### ISSUE TITLE
Getting Unexpected Execution Error msg

### ISSUE THREAD

**Issue by VarunSaiTeja** [dalrankov/FluentChoco#2]
```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addUser"
      ],
      "extensions": {
        "message": "Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.",
        "stackTrace": "   at FluentChoco.ArgumentValidationOptions`1..ctor(IInputField argument, TArgument instance)\r\n   at FluentChoco.FluentValidationMiddleware.Invoke(IMiddlewareContext context)\r\n   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)\r\n   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
      }
    }
  ]
}
```

```
    public class AddUserInput
    {
        [Required, MinLength(4, ErrorMessage = "Username must be atleast 4 characters.")]
        public string UserName { get; set; }

        [Required, RegularExpression(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", ErrorMessage = "Email Id format is invalid")]
        public string Email { get; set; }

        [Required, RegularExpression(@"^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$", ErrorMessage = "Password must be atleast 8 characters, at least one uppercase letter, one lowercase letter, one number and one special character.")]
        public string Password { get; set; }
    }
}
```

Startup.cs
```
services.RegisterFluentValidators<Startup>();

services.AddGraphQLServer()
                .UseFluentValidation<CustomErrorBuilder>()
```

CustomErrorBuilder
```
public class CustomErrorBuilder
    : IValidationErrorBuilder
    {
        public IErrorBuilder BuildError(
            IErrorBuilder builder,
            ValidationFailure failure,
            IInputField argument,
            IMiddlewareContext context)
        {
            return builder.SetMessage(failure.ErrorMessage);
        }
    }
```

```
    [ExtendObjectType(Name = "Mutation")]
    public class UserMutations : BaseGraphQL
    {
        public async Task<int> AddUser(AddUserInput input, [Service] MailService mailService, [Service] UserManager<AppUser> userManager)
        {
            //Code for adding user
        }
     }
```

Did I miss anything ?

**Comment by dalrankov** [comment]
@VarunSaiTeja I suppose you're using HC 11.0.9 and FluentChoco 2.0.0, which uses HC 11.0.7, so there's the problem. I've released v2.0.1 with HC 11.0.9. It is available for download in NuGet. Thanks for reporting this.

**Comment by VarunSaiTeja** [comment]
@dalrankov  I had updated to v2.0.1. Not getting any exception now.
But inputs are still not validating. Did I miss anything in the code?

**Comment by dalrankov** [comment]
It is because validation attributes are not supported by FluentChoco. As the name and description say, it is using FluentValidation library to validate input objects. What you must do is create your own model validators by extending AbstractValidator class from FluentValidation library, and register those validators in your services either manually or by using extension method available in readme of this repository.
